---
title: "Code for My Map"
author: "Andy Grogan-Kaylor"
format: html
---

```{r}
#| output: false

library(sf) # simple features

library(ggplot2) # beautiful graphs

MICS <- read_sf("MICS/MICS.shp") 

global_data <- read_sf("wrld_simpl/wrld_simpl.shp")

```

```{r}
#| fig-cap: "Countries in MICS"
#| warning: false
#| message: false
#| eval: false
#| fig-dpi: 600

ggplot(global_data) +
  geom_sf() +
  geom_sf(data = MICS,
          color = "#5b92e5",
          fill = "#5b92e5",
          alpha = .5,
          linewidth = .5) +
  theme_minimal()

```

```{r}
#| fig-cap: "Countries in MICS"
#| message: false
#| fig-height: 5

library(leaflet)

leaflet() %>%
  setView(0, 0, zoom = 1.5) %>%
  # addTiles() %>%
  addProviderTiles(providers$Esri.WorldImagery) %>%
  addPolygons(data = MICS, 
              fillOpacity = .75, 
              color = "#5b92e5", 
              label = MICS$NAME,
              highlightOptions = highlightOptions(color = "red", 
                                                  weight = 2,
                                                  bringToFront = TRUE)) 

```